image: gradle:jdk11-slim

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle
    - build

build:
  stage: build
  script: gradle --build-cache assemble

test:
  stage: test
  script:
    - gradle --build-cache check
    - cat core/build/reports/jacoco/test/html/index.html

pages:
  only:
    - tags
  stage: deploy
  script:
    - mv core/build/docs/javadoc public
  artifacts:
    paths:
      - public
  cache:
    policy: pull
    paths:
      - build/docs/

bintray:
  only:
    - tags
  stage: deploy
  script: gradle bintrayUpload
  cache:
    policy: pull
